name: CI - Build and Test

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ./order-service/package-lock.json,./order-webapp/package-lock.json

      - name: Install dependencies (order-service)
        working-directory: ./order-service
        run: npm install

      - name: Run unit tests (order-service)
        working-directory: ./order-service
        run: npm test

      - name: Install dependencies (order-webapp)
        working-directory: ./order-webapp
        run: npm install

      - name: Run unit tests (order-webapp)
        working-directory: ./order-webapp
        run: npm test
